### ISSUE TITLE
Camera not working after renaming package

### ISSUE THREAD

**Issue by jonnaah** [aqnouch/Signal-Setup-Guide#19]
Hi, I just renamed my app package name and I followed all steps, but for some reason the app crashes all time when I tap the camera icon. I don't know why this happens and need your help. Thanks in advance! @aqnouch

**Comment by madeindra** [comment]
@jonnaah rebuild the native code, you need NDK

**Comment by jonnaah** [comment]
Hi, I have installed NDK, but when I try to run 'ndk-build' I get this
error:

Android NDK: Please define the NDK_PROJECT_PATH variable to point to
it.c:\ndk\build/core/build-local.mk:148: *** Android NDK: Aborting
.  Stop.

**Comment by jonnaah** [comment]
Thank you, I only have now one problem: 'ndk-build' is not recognized as an
internal or external command,
operable program or batch file.

**Comment by jonnaah** [comment]
Hi, I still have many problems, what I need to do? When I replaced the line
of code, I got this error:

Android NDK “ndk-build” recognized as an internal or external command batch file


And then I added the NDK path to variable's value in the environment
variable(System variable) and now I get the same error:

C:\Users\User\AndroidStudioProjects\Project>ndk-build
Android NDK: Could not find application project directory !
Android NDK: Please define the NDK_PROJECT_PATH variable to point to it.
        C:\android-ndk-r19\build\\..\build\core\build-local.mk:151:
*** Android NDK: Aborting    .  Stop.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Ei
viruksia. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jonnaah** [comment]
Ok I don't need to build NDK, now the camera works! Thank you!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Ei
viruksia. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
