### ISSUE TITLE
Where's location to rename application name?

### ISSUE THREAD

**Issue by sayamahendra** [aqnouch/Signal-Setup-Guide#22]
Hi i tried to change app name in gradle setting, but it's still named Signal, how to change the app name?

**Comment by aqnouch** [comment]
You must change the first line in
`app/src/main/res/values/strings.xml`

Like this: 
<string name="app_name" translatable="false">XXXXXXXX</string>

**Comment by sayamahendra** [comment]
yes i've found it. i thought it located on gradle. thanks in advance.
