### ISSUE TITLE
License revision for earlier author

### ISSUE THREAD

**Issue by madeindra** [aqnouch/Signal-Setup-Guide#3]
Hi there, good day to yo!

I want to ask if this repo is forked version of the guide I wrote (https://github.com/madeindra/setup-guide) ?

I can see that some sentences were still identical to what I wrote, so I guess I just want to remind you to please don't alter the name listed in MIT License.

As it state: 

```
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
```

So yeah, you can add a name under the first author, but not deleting it completely.

I hope to spread the guide so more people can be helped through this, anyone is welcome to open in issue over my repo too if needed.

Thanks in advance!

**Comment by aqnouch** [comment]
Hi,
Indeed, I copied many sentences from your guide, but I kept the original license as the MIT license doesn't specify attribution beyond maintaining the copyright notice.

As requested I updated the License to include this statement:

_Copyright for portions of project Signal-Setup-Guide are held by [Made Indra, 2020] as part of project Setup Guide for Signal. All other copyright for this project are held by [AQNOUCH Mohammed, 2020]._

**Comment by aqnouch** [comment]
Is this ok for you ?

**Comment by madeindra** [comment]
Thanks for your consideration
