### ISSUE TITLE
Give credit to the original Repo

### ISSUE THREAD

**Issue by ajaymota** [aqnouch/Signal-Setup-Guide#30]
It seems like you have used the guide written by github user madeindra without attributing or crediting him.
This is not a fair practise, so I request you to please fix it.

Link to the original guide which has a better documentation than your guide can be found here 
https://github.com/madeindra/signal-setup-guide

In case I am wrong, I would be happy to change my mind.

**Comment by aqnouch** [comment]
Hello,

I mentioned the original author in the License, even if it is not required by the MIT license.

_Copyright for portions of project Signal-Setup-Guide are held by Made Indra as part of project Setup Guide for Signal. All other copyright for this project are held by [AQNOUCH Mohammed]._

**Comment by ajaymota** [comment]
Hi, 

Thanks for replying to this issue. However, there is one problem with this approach. When you pull the original author's repo and reupload the changes as your own repo **without forking it**, you rewrite the repo's history.
This makes it difficult for a user to look at a repo and figure out the parts you improved over the original repo's codebase. I do like it that you mentioned the original author's name in the license but simply forking his repo and making changes to it later would've sent a stronger message of endorsement and collaboration. 
Lastly, 44 forks of your repo today have lost access to the version control history of madeindra's commits, so their path to learning his efforts is obscured. So that's the principal flaw I wished to point out with this approach of crediting.
